name: Release Container

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the new release container (e.g. latest, v1.0.0)'
        required: true
        default: 'latest'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/isosafrasaurus/3d-1d:0
      options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prepare Working Directory
        run: |
          mkdir -p /home/jovyan/work
          cp -R /github/workspace/* /home/jovyan/work/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: /home/jovyan/work
          push: true
          tags: ghcr.io/isosafrasaurus/3d-1d:${{ github.event.inputs.tag }}
